In [1]:
import numpy as np

In [2]:
N = 100 # Number of samples
D = 2 # Number of features

In [3]:
X = np.random.randn(N,D)
X

array([[ 8.64908641e-01,  1.16187217e+00],
       [ 2.01260821e+00, -1.16897175e-01],
       [-5.54634528e-01, -2.73631056e-01],
       [-2.57756580e-01, -1.22486230e+00],
       [-7.89702180e-01,  1.09715995e+00],
       [ 4.33568479e-01, -1.55709537e+00],
       [ 2.43312976e+00, -1.27405101e+00],
       [-1.23490767e+00,  5.84455589e-01],
       [ 1.40658866e-01, -5.72202036e-01],
       [-2.33580841e-01,  7.39153767e-01],
       [-1.42226401e+00, -1.63362637e-01],
       [ 2.18125037e-01, -7.79279630e-01],
       [-5.35686491e-01, -1.18287537e+00],
       [-1.36711284e-01, -2.67928115e-01],
       [ 1.06578327e+00,  2.21641561e-01],
       [ 1.92012387e+00,  7.53867810e-01],
       [ 2.69011963e-05, -1.47776850e+00],
       [-1.58225012e-01, -4.30998628e-02],
       [-1.53478234e+00, -4.40884866e-01],
       [ 9.34752986e-01,  7.02962837e-01],
       [ 1.58122663e+00, -2.37571753e-02],
       [ 8.90498293e-01, -7.08633134e-01],
       [ 6.16912921e-01,  1.17839213e+00],
       [ 1.

In [4]:
# Subtract 2 from the first 50 rows
X[:50, :] = X[:50, :] - 2*np.ones((50,D))

In [5]:
# Add 2 to the last 50 rows
X[50:, :] = X[50:, :] + 2*np.ones((50,D))

In [6]:
X

array([[-1.13509136, -0.83812783],
       [ 0.01260821, -2.11689718],
       [-2.55463453, -2.27363106],
       [-2.25775658, -3.2248623 ],
       [-2.78970218, -0.90284005],
       [-1.56643152, -3.55709537],
       [ 0.43312976, -3.27405101],
       [-3.23490767, -1.41554441],
       [-1.85934113, -2.57220204],
       [-2.23358084, -1.26084623],
       [-3.42226401, -2.16336264],
       [-1.78187496, -2.77927963],
       [-2.53568649, -3.18287537],
       [-2.13671128, -2.26792812],
       [-0.93421673, -1.77835844],
       [-0.07987613, -1.24613219],
       [-1.9999731 , -3.4777685 ],
       [-2.15822501, -2.04309986],
       [-3.53478234, -2.44088487],
       [-1.06524701, -1.29703716],
       [-0.41877337, -2.02375718],
       [-1.10950171, -2.70863313],
       [-1.38308708, -0.82160787],
       [-0.50205472, -0.87455834],
       [-2.26142243, -1.58958983],
       [-0.34766294, -1.63743611],
       [-2.98811655, -2.98296993],
       [-1.37069934, -2.73336753],
       [-1.04460719,

In [7]:
# Create array of targets
T = np.array([0]*50 + [1]*50)

In [8]:
# Concatenate a column of ones
ones = np.array([[1]*N]).T
Xb = np.concatenate((ones, X), axis=1)

In [9]:
# randomly initialize the weights
w = np.random.randn(D+1)
w

array([ 0.04629922, -0.13834711, -0.25636705])

In [10]:
# calculate the model output
z = Xb.dot(w)
z

array([ 0.41820419,  0.58725758,  0.98260961,  1.18540175,  0.6637049 ,
        1.17493253,  0.82573575,  0.8567383 ,  0.96296153,  0.6785481 ,
        1.07437445,  1.00533218,  1.21308848,  0.92332909,  0.6314579 ,
        0.37681708,  1.21457496,  0.86866689,  1.16108859,  0.52619065,
        0.62305995,  0.89419985,  0.4482785 ,  0.33996498,  0.76667893,
        0.51418204,  1.22443171,  0.93667687,  0.73187636,  0.89453749,
        0.5812484 ,  0.90284557,  0.87939482,  1.01130509,  0.35385187,
        0.3507063 ,  0.70633341,  0.97057348,  0.8104969 ,  0.88770594,
        0.62482668,  0.71501109,  0.67728116,  0.53359135,  0.5103953 ,
        1.40115241,  1.08145196,  0.31899584,  1.13680412,  0.86172615,
       -0.39526295, -0.55477024, -0.82962338, -1.05757236, -0.63599889,
       -0.97178623, -0.3465938 , -0.54506973, -0.89054804, -0.9319875 ,
       -0.77965276, -0.46422686, -0.60833796, -0.60600649, -0.61546458,
       -0.78692302, -1.12501228, -0.70754216, -0.71379879, -0.53

In [11]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [12]:
Y = sigmoid(z)
Y

array([0.60305345, 0.64273566, 0.72762571, 0.76591766, 0.66009215,
       0.76403544, 0.69545252, 0.70197874, 0.72371436, 0.66341457,
       0.74542793, 0.73210566, 0.77084496, 0.71571994, 0.65281996,
       0.59310519, 0.77110743, 0.70446823, 0.76153046, 0.6285942 ,
       0.65091417, 0.70975611, 0.61022985, 0.58418202, 0.68280204,
       0.62578633, 0.77284251, 0.71842791, 0.67521689, 0.70982566,
       0.64135461, 0.71153392, 0.7066968 , 0.73327548, 0.58755133,
       0.58678884, 0.66959047, 0.72523379, 0.69221538, 0.70841653,
       0.6513155 , 0.67150748, 0.66313161, 0.63032035, 0.62489914,
       0.80236669, 0.74676865, 0.57907951, 0.75709239, 0.70302117,
       0.402451  , 0.36475839, 0.30372471, 0.25777365, 0.34615155,
       0.27452461, 0.41420866, 0.36700902, 0.29099674, 0.28252167,
       0.31439473, 0.38598358, 0.35243842, 0.35297071, 0.35081366,
       0.31282974, 0.24508274, 0.33014216, 0.32875999, 0.36985396,
       0.40432154, 0.25872897, 0.30847311, 0.45699081, 0.26877

In [13]:
def cross_entropy(T, Y):
    E = 0
    for i in range(N):
        if T[i] == 1:
            E -= np.log(Y[i])
        else:
            E -= np.log(1 - Y[i])
    return E

In [14]:
print(cross_entropy(T, Y))

115.73491947161821


In [15]:
# Closed form solution to logistic regression - bias is 0 and both weights are 4
w = np.array([0, 4, 4])

In [16]:
z = Xb.dot(w)
Y = sigmoid(z)

In [17]:
print(cross_entropy(T,Y))

0.18014696106867498
