In [1]:
import numpy as np

In [2]:
N = 100 # Number of samples
D = 2 # Number of features

In [12]:
X = np.random.randn(N,D)
X

array([[ 0.71044618,  1.04044401],
       [ 0.89453283, -0.70267032],
       [ 0.70481802, -1.64161539],
       [-0.27691821, -0.50647283],
       [ 1.37644621, -1.06588095],
       [ 0.7128508 , -0.00352755],
       [-0.33413277, -0.06875676],
       [ 0.86661884, -0.55184439],
       [-0.45783502, -0.96311491],
       [ 0.23430911, -0.44043538],
       [ 0.92691799,  0.54336489],
       [-0.21240217, -0.16883514],
       [ 0.06739695, -0.0591113 ],
       [ 0.3227933 , -2.22980331],
       [ 0.23530509, -1.46153152],
       [ 0.33736066, -1.1361949 ],
       [ 0.97736338, -1.19287272],
       [-0.91128173, -1.03394583],
       [-1.02662681, -0.48840892],
       [ 1.46552741,  0.60094002],
       [ 0.47580653, -1.8317124 ],
       [-0.77000119, -1.3334861 ],
       [ 0.14923173,  0.93971604],
       [-0.1345636 ,  0.20042955],
       [-0.12689599,  1.87398032],
       [ 0.25719716, -0.00667928],
       [-1.20664342, -0.60117585],
       [ 0.95466726, -1.48408329],
       [-1.69622898,

In [13]:
# Subtract 2 from the first 50 rows
X[:50, :] = X[:50, :] - 2*np.ones((50,D))

In [14]:
# Add 2 to the last 50 rows
X[50:, :] = X[50:, :] + 2*np.ones((50,D))

In [15]:
X

array([[-1.28955382, -0.95955599],
       [-1.10546717, -2.70267032],
       [-1.29518198, -3.64161539],
       [-2.27691821, -2.50647283],
       [-0.62355379, -3.06588095],
       [-1.2871492 , -2.00352755],
       [-2.33413277, -2.06875676],
       [-1.13338116, -2.55184439],
       [-2.45783502, -2.96311491],
       [-1.76569089, -2.44043538],
       [-1.07308201, -1.45663511],
       [-2.21240217, -2.16883514],
       [-1.93260305, -2.0591113 ],
       [-1.6772067 , -4.22980331],
       [-1.76469491, -3.46153152],
       [-1.66263934, -3.1361949 ],
       [-1.02263662, -3.19287272],
       [-2.91128173, -3.03394583],
       [-3.02662681, -2.48840892],
       [-0.53447259, -1.39905998],
       [-1.52419347, -3.8317124 ],
       [-2.77000119, -3.3334861 ],
       [-1.85076827, -1.06028396],
       [-2.1345636 , -1.79957045],
       [-2.12689599, -0.12601968],
       [-1.74280284, -2.00667928],
       [-3.20664342, -2.60117585],
       [-1.04533274, -3.48408329],
       [-3.69622898,

In [16]:
# Create array of targets
T = np.array([0]*50 + [1]*50)

In [24]:
# Concatenate a column of ones
ones = np.array([[1]*N]).T
Xb = np.concatenate((ones, X), axis=1)

In [26]:
# randomly initialize the weights
w = np.random.randn(D+1)
w

array([-0.12516739, -0.93243277, -0.0229311 ])

In [29]:
# calculate the model output
z = Xb.dot(w)
z

array([ 1.09925853,  0.96758163,  1.16600897,  2.05538195,  0.52655862,
        1.1209558 ,  2.09869336,  0.99015094,  2.23454601,  1.57718252,
        0.90881169,  1.98748268,  1.72407271,  1.53570914,  1.5996687 ,
        1.49704841,  0.90158858,  2.65897882,  2.75402059,  0.40527435,
        1.38390593,  2.53411299,  1.62486308,  1.9064358 ,  1.86090991,
        1.54589446,  2.92445985,  0.92942897,  3.35619537,  1.94014672,
        1.09383477,  2.19605895,  2.06229167,  3.06412505,  2.23738082,
        3.40161053,  1.5001852 ,  1.18737372,  1.76342673,  2.75098739,
        4.37773117,  0.98968937,  1.48907975,  1.53925071,  1.02081106,
        2.25386225,  1.61621116,  2.92749653,  1.29534234,  2.05813241,
       -1.53042154, -1.49547563, -1.31994951, -1.87568622, -1.39641724,
       -1.39773438, -0.92649125, -2.57256597, -0.79208587, -2.07080039,
       -2.14105233, -2.2812984 , -1.27527219, -2.28600887, -2.25870827,
       -2.60868889, -1.87616366, -1.40027525, -2.90685135, -2.84

In [30]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [31]:
Y = sigmoid(z)
Y

array([0.75012115, 0.7246372 , 0.76242286, 0.88649031, 0.62868011,
       0.75416596, 0.89077612, 0.72911774, 0.90330914, 0.82880512,
       0.71275694, 0.87947656, 0.84865268, 0.82284009, 0.83197208,
       0.81713384, 0.71127585, 0.93456224, 0.94014002, 0.59995422,
       0.79961758, 0.92649893, 0.83546472, 0.8706182 , 0.86540297,
       0.82431997, 0.94904241, 0.71695942, 0.96630713, 0.87436826,
       0.74910315, 0.89989504, 0.88718374, 0.95538844, 0.90355646,
       0.96775483, 0.8176021 , 0.76627103, 0.85363831, 0.93996909,
       0.98760184, 0.72902656, 0.81594011, 0.82335577, 0.73513055,
       0.90498316, 0.83427194, 0.94918907, 0.78505006, 0.88676678,
       0.17793202, 0.18310129, 0.21082669, 0.13288515, 0.19838526,
       0.19817588, 0.28363711, 0.07092503, 0.31172097, 0.11196743,
       0.10517031, 0.09268371, 0.21835608, 0.09228835, 0.09460095,
       0.06858131, 0.13283015, 0.19777244, 0.05181591, 0.0548386 ,
       0.07596681, 0.22757422, 0.02547246, 0.20261758, 0.04420

In [32]:
def cross_entropy(T, Y):
    E = 0
    for i in range(N):
        if T[i] == 1:
            E -= np.log(Y[i])
        else:
            E -= np.log(1 - Y[i])
    return E

In [34]:
print(cross_entropy(T, Y))

211.70909405846703


In [37]:
# Closed form solution to logistic regression
w = np.array([0, 4, 4])

In [ ]:
z = Xb..dot(w)