In [26]:
import numpy as np

In [27]:
N = 100
D = 2

In [28]:
X = np.random.randn(N,D)
X

array([[-1.61115495,  0.0841777 ],
       [-0.14822315, -1.42880611],
       [ 0.30708979, -0.34070231],
       [ 0.40633866, -0.63886879],
       [-1.10670841, -0.0668654 ],
       [-0.5237388 , -1.1943241 ],
       [ 0.24644058, -0.31342995],
       [ 0.16207095,  0.28930425],
       [ 0.90983789,  0.47554974],
       [ 2.51451047, -0.63954242],
       [ 1.06023466,  0.19157122],
       [-0.14898036, -1.73933399],
       [ 0.45410366, -1.35284544],
       [-0.32767109,  1.21814594],
       [ 1.54228456, -0.57528394],
       [ 0.66317226, -0.81230177],
       [-0.82649669,  0.03218754],
       [-0.34801385, -0.41744926],
       [-0.22103941, -0.91126478],
       [ 0.08736154,  0.56808425],
       [ 0.32297119, -0.00875718],
       [ 0.05062144, -0.13356374],
       [ 0.07319912,  0.0359303 ],
       [ 0.44077877,  0.07690722],
       [ 1.18179106, -1.12602989],
       [-1.35645496,  0.1489079 ],
       [-0.61988048, -0.10036171],
       [-0.90741211,  0.49714619],
       [ 0.78385835,

In [35]:
ones = np.array([[1]*N]).T
Xb = np.concatenate((ones, X), axis=1)
Xb

array([[ 1.        , -1.61115495,  0.0841777 ],
       [ 1.        , -0.14822315, -1.42880611],
       [ 1.        ,  0.30708979, -0.34070231],
       [ 1.        ,  0.40633866, -0.63886879],
       [ 1.        , -1.10670841, -0.0668654 ],
       [ 1.        , -0.5237388 , -1.1943241 ],
       [ 1.        ,  0.24644058, -0.31342995],
       [ 1.        ,  0.16207095,  0.28930425],
       [ 1.        ,  0.90983789,  0.47554974],
       [ 1.        ,  2.51451047, -0.63954242],
       [ 1.        ,  1.06023466,  0.19157122],
       [ 1.        , -0.14898036, -1.73933399],
       [ 1.        ,  0.45410366, -1.35284544],
       [ 1.        , -0.32767109,  1.21814594],
       [ 1.        ,  1.54228456, -0.57528394],
       [ 1.        ,  0.66317226, -0.81230177],
       [ 1.        , -0.82649669,  0.03218754],
       [ 1.        , -0.34801385, -0.41744926],
       [ 1.        , -0.22103941, -0.91126478],
       [ 1.        ,  0.08736154,  0.56808425],
       [ 1.        ,  0.32297119, -0.008

In [36]:
# randomly initialize a weight vector
w = np.random.randn(D+1)
w

array([ 0.65255659, -0.22678836, -1.20777161])

In [37]:
# calculate the dot product between each row of x and w
z = Xb.dot(w)
z.shape

(100,)

In [38]:
def sigmoid(z):
    return 1/(1 + np.exp(-z))

In [39]:
print(sigmoid(z))

[0.71428359 0.91772597 0.72995667 0.79117313 0.72796125 0.90148239
 0.72615844 0.56620578 0.46800888 0.70155551 0.54506077 0.94197265
 0.89875794 0.32204852 0.73058567 0.81506024 0.69021427 0.77480862
 0.8585484  0.48666016 0.64333925 0.69048565 0.64395238 0.61294461
 0.85126117 0.68575296 0.71388995 0.56412197 0.49204505 0.50742129
 0.84832777 0.83055954 0.33357005 0.24547166 0.22650393 0.81156409
 0.82120429 0.71459876 0.78240974 0.6579666  0.80793393 0.09510585
 0.96192508 0.82528738 0.04257725 0.66924945 0.17993421 0.58786174
 0.68609455 0.86810552 0.72101146 0.71753036 0.75348624 0.20797462
 0.15134286 0.87663723 0.35843413 0.2829109  0.79276334 0.93625022
 0.32417383 0.79876887 0.72094508 0.80177744 0.59610042 0.94210786
 0.96237499 0.76615545 0.28736245 0.53835908 0.66317515 0.4098286
 0.44715708 0.684891   0.67607758 0.44344493 0.28958552 0.38586877
 0.65065601 0.80556566 0.53778989 0.8219127  0.30629878 0.72205506
 0.11006702 0.78712539 0.77070035 0.94279548 0.84262807 0.97966